title: test
exclude:
  - _RIOT
  - _tools
  - Makefile
  - README.md

sass:
    sass_dir: _sass
collections:
    use_cases:
        output: true
    faqs:
        output: true

defaults:
  - scope:
      path: ""
      type: "use_cases"
    values:
      layout: "use-case"
